import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import 'mapbox-gl/dist/mapbox-gl.css';
import Map from '@/components/map/map';

export default function Home() {
  return (
    <>
      <Head>
        <title>Map My Model</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Map></Map>
      </main>
    </>
  )
}
